#!/usr/bin/env bash
#
# Tool to package and publish Python projects on PyPI
#
# It requires 'pypi' and 'testpypi' sections to be defined in .pypirc.
#
# Author: Peter Pakos <peter.pakos@wandisco.com>
# Copyright (C) 2018 WANdisco
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -euo pipefail

readonly APP_NAME="$(basename "$0")"
readonly APP_VER="1.0.0"
test=""

display_version() {
  printf "%s version %s\\n" "$APP_NAME" "$APP_VER"
}

display_help() {
  display_version
  cat <<HELP
Usage: ${APP_NAME} [OPTIONS]
AVAILABLE OPTIONS:
-v  Print version number
-h  Print this help summary page
-t  Publish to Test PyPI
HELP
}

get_opts() {
  while getopts ":vht" opt; do
    case $opt in
      v)
        display_version
        exit 0
        ;;
      h)
        display_help
        exit 0
        ;;
      t)
        test="test"
        ;;
      :)
        die "Option -${OPTARG} requires an argument"
        ;;
      *)
        die "Invalid option -${OPTARG}"
        ;;
    esac
  done
}

pip_twine() {
  if ! pip list | grep -q '^twine\s'; then
    pip -q install twine
  fi
}

md_to_rst() {
  for f in *.md; do
    pandoc -s -f gfm -t rst "$f" > "${f%.md}.rst"
  done
}

cleanup() {
  rm -rf ./build ./dist ./*.egg-info ./__pycache__
  for f in *.md; do
    rm -f "${f%.md}.rst"
  done
}

main() {
  get_opts "$@"
  pip_twine
  cleanup
  md_to_rst
  python setup.py package
  twine upload -r "${test}pypi" --skip-existing dist/* || true
  cleanup
}

main "$@"
